### ISSUE TITLE
JavaDiagnosticListener has problems with some source file locations

### ISSUE THREAD

**Issue by Darkyenus** [Darkyenus/wemi#23]
```
[17:45:12 ERROR] CLI: Error while evaluating run
wemi.WemiException: Unhandled exception
        at wemi.boot.Task.evaluateKey(Task.kt:114)
        at wemi.boot.CLI.evaluateAndPrint(CLI.kt:362)
        at wemi.boot.CLI.evaluateAndPrint$default(CLI.kt:351)
        at wemi.boot.Launch.main(Launch.kt:414)
Caused by: java.lang.RuntimeException: java.nio.file.FileSystemNotFoundException
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:163)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
        at wemi.KeyDefaults$CompileJavaKotlin$1.invoke(KeyDefaults.kt:444)
        at wemi.KeyDefaults$CompileJavaKotlin$1.invoke(KeyDefaults.kt:93)
        at wemi.EvalScope.getKeyValue(Evaluation.kt:180)
        at wemi.EvalScope.get(Evaluation.kt:229)
        at wemi.EvalScope.get$default(Evaluation.kt:227)
        at wemi.KeyDefaults$internalClasspath$1.invoke(KeyDefaults.kt:203)
        at wemi.KeyDefaults$internalClasspath$1.invoke(KeyDefaults.kt:93)
        at wemi.EvalScope.getKeyValue(Evaluation.kt:180)
        at wemi.EvalScope.get(Evaluation.kt:229)
        at wemi.EvalScope.get$default(Evaluation.kt:227)
        at wemi.KeyDefaults.doRun(KeyDefaults.kt:481)
        at wemi.KeyDefaults.access$doRun(KeyDefaults.kt:93)
        at wemi.KeyDefaults$Run$1.invoke(KeyDefaults.kt:511)
        at wemi.KeyDefaults$Run$1.invoke(KeyDefaults.kt:93)
        at wemi.EvalScope.getKeyValue(Evaluation.kt:180)
        at wemi.EvalScope.get(Evaluation.kt:229)
        at wemi.boot.Task.evaluateKey(Task.kt:105)
        ... 3 more
Caused by: java.nio.file.FileSystemNotFoundException
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:169)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:155)
        at java.base/java.nio.file.Path.of(Path.java:208)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at wemi.KeyDefaults$JavaDiagnosticListener$1.report(KeyDefaults.kt:246)
        at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$WrappedDiagnosticListener.report(ClientCodeWrapper.java:736)
        at jdk.compiler/com.sun.tools.javac.util.Log.writeDiagnostic(Log.java:734)
        at jdk.compiler/com.sun.tools.javac.util.Log$DefaultDiagnosticHandler.report(Log.java:701)
        at jdk.compiler/com.sun.tools.javac.util.Log.report(Log.java:678)
        at jdk.compiler/com.sun.tools.javac.util.AbstractLog.mandatoryNote(AbstractLog.java:252)
        at jdk.compiler/com.sun.tools.javac.util.MandatoryWarningHandler.logMandatoryNote(MandatoryWarningHandler.java:267)
        at jdk.compiler/com.sun.tools.javac.util.MandatoryWarningHandler.reportDeferredDiagnostic(MandatoryWarningHandler.java:178)
        at jdk.compiler/com.sun.tools.javac.comp.Check.reportDeferredDiagnostics(Check.java:260)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.reportDeferredDiagnostics(JavaCompiler.java:1732)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:988)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
        ... 22 more
        in 3 seconds 862 ms
```

**Comment by Darkyenus** [comment]
Fixed by 930c987f57187e5638b38bad17115fd1c0fae0db.
